project:
  type: book
  output-dir: docs

book:
  title: "Laboratorio di Testing Psicologico"
  subtitle: ""
  author: "Corrado Caudek"
  date: "last-modified"
  search: true
  # cover-image: figures/icon_course.png
  repo-url: https://github.com/ccaudek/lab-test-psi/
  repo-actions: [edit]
  site-url: https://ccaudek.github.io/lab-test-psi/intro.html
  page-footer:
    left: |
      Laboratorio di Testing Psicologico è stato scritto da Corrado Caudek.
    right: |
      Questo libro è stato realizzato con <a href="https://quarto.org/">Quarto</a>.
  sidebar:
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd
    - prefazione.qmd

    - part: "Programmazione"
      chapters:
        - cal_lab_test_psi_2025.ipynb

    - part: "Modulo 1"
      chapters:
        - units/unit_1/01_intro_r.ipynb

    - part: "Modulo 2"
      chapters:
        - units/unit_2/01_assignment_02.ipynb
        - units/unit_2/02_descriptive_stats.qmd
        - units/unit_2/03_careless.ipynb
        - units/unit_2/hw1a.qmd
        - units/unit_2/hw1b.qmd
        - units/unit_2/hw2a.qmd

    - part: "Modulo 3"
      chapters:
        - units/unit_3/01_assignment_03.ipynb
        - units/unit_3/02_ctt.ipynb

    - part: "Modulo 4"
      chapters:
        - units/unit_4/01_assignment_04.ipynb

    - 99-references.qmd

crossref:
  appendix-title: "Appendice"

biblio-style: apalike
bibliography: ./references.bib

lang: it

format:
  html:
    toc: true
    toc-depth: 5
    format-options:
      html:
        table-class: table table-striped table-hover table-bordered
    smooth-scroll: true
    theme:
      light:
        - cosmo
      dark:
        - darkly
    highlight-style: github
    code-link: true
    code-overflow: wrap
    author-meta: "Corrado Caudek"
    callout-appearance: simple

editor: source
url_sanitize: false

website:
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TP2WLBPMS6"
    anonymize-ip: true
